language: ruby

gemfile:
- Gemfile
- chef-12.Gemfile

sudo: required

dist: trusty

rvm:
- 2.4.2

env:
- SUITE=chefspec
- SUITE=centos
- SUITE=ubuntu

services:
- docker

script:
- bundle exec ./.travis.sh
